name: resume-matcher-website

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5175:80
    networks:
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true
